<?php
/**
 * Configure fast-kalk lead widget + SMTP for local WP runtime (:8091).
 * Run: php scripts/configure-local.php
 */

$repoRoot = dirname(__DIR__);
$wpRoot = $repoRoot . '/../kalk-top/.runtime-wp/wordpress';
$muSource = $repoRoot . '/wp-content/mu-plugins/topinstal-wp-smtp.php';
$muTargetDir = $wpRoot . '/wp-content/mu-plugins';
$muTarget = $muTargetDir . '/topinstal-wp-smtp.php';
$pluginSource = $repoRoot . '/wp-content/plugins/topinstal-lead-widget';
$pluginTarget = $wpRoot . '/wp-content/plugins/topinstal-lead-widget';
$secretsPath = $repoRoot . '/config/local-secrets.env';
$cieploEnv = $repoRoot . '/../cieplo-orchestrator/.env';

/**
 * @param string $path
 * @return array<string,string>
 */
function parse_dotenv($path) {
    $out = array();
    if (!is_readable($path)) {
        return $out;
    }
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') {
            continue;
        }
        $eq = strpos($line, '=');
        if ($eq === false) {
            continue;
        }
        $key = trim(substr($line, 0, $eq));
        $value = trim(substr($line, $eq + 1));
        if ($key !== '') {
            $out[$key] = $value;
        }
    }
    return $out;
}

/**
 * @param string $dir
 * @param string $link
 * @param string $target
 * @return void
 */
/**
 * @param string $link
 * @param string $target
 * @return void
 */
function ensure_plugin_link($link, $target) {
    if (PHP_OS_FAMILY === 'Windows') {
        if (is_dir($link) || is_link($link)) {
            return;
        }
        $parent = dirname($link);
        if (!is_dir($parent)) {
            mkdir($parent, 0755, true);
        }
        $cmd = 'cmd /c mklink /J "' . str_replace('/', '\\', $link) . '" "' . str_replace('/', '\\', $target) . '"';
        exec($cmd, $output, $code);
        if ($code !== 0 && !is_dir($link)) {
            fwrite(STDERR, "Failed to junction plugin: {$link}\n");
            exit(1);
        }
        return;
    }
    symlink($target, $link);
}

function ensure_symlink($dir, $link, $target) {
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    if (is_link($link)) {
        return;
    }
    if (is_file($link)) {
        if (realpath($link) === realpath($target)) {
            return;
        }
        @unlink($link);
    }
    if (PHP_OS_FAMILY === 'Windows') {
        if (!is_file($link)) {
            $cmd = 'cmd /c mklink "' . str_replace('/', '\\', $link) . '" "' . str_replace('/', '\\', $target) . '"';
            exec($cmd, $output, $code);
            if ($code !== 0 && !is_file($link)) {
                copy($target, $link);
            }
        }
        return;
    }
    symlink($target, $link);
}

$gmailEnvPaths = array(
    $repoRoot . '/../gmail-agent/.env.vps',
    $repoRoot . '/../gmail-agent/.env.local-vps',
);
$gmailEnv = array();
foreach ($gmailEnvPaths as $gmailEnvPath) {
    if (is_readable($gmailEnvPath)) {
        $gmailEnv = array_merge($gmailEnv, parse_dotenv($gmailEnvPath));
    }
}
$env = parse_dotenv($cieploEnv);
$env = array_merge($env, $gmailEnv);
$smtpKeys = array('SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASSWORD', 'SMTP_FROM', 'SMTP_USE_SSL', 'SMTP_USE_TLS');
$lines = array('# Generated by configure-local.php — do not commit');
foreach ($smtpKeys as $key) {
    if (isset($env[$key]) && $env[$key] !== '') {
        $lines[] = $key . '=' . $env[$key];
    }
}
if (!is_dir(dirname($secretsPath))) {
    mkdir(dirname($secretsPath), 0755, true);
}
file_put_contents($secretsPath, implode("\n", $lines) . "\n");
echo "Wrote {$secretsPath}\n";

ensure_symlink($muTargetDir, $muTarget, $muSource);
echo "Linked mu-plugin: {$muTarget}\n";

if (is_dir($pluginTarget) && !is_link($pluginTarget) && count(scandir($pluginTarget)) <= 2) {
    rmdir($pluginTarget);
}
$pluginTargetReal = (is_dir($pluginTarget) || is_link($pluginTarget)) ? realpath($pluginTarget) : false;
$pluginSourceReal = realpath($pluginSource);
if ($pluginTargetReal !== false && $pluginSourceReal !== false && $pluginTargetReal !== $pluginSourceReal) {
    if (PHP_OS_FAMILY === 'Windows') {
        exec('cmd /c rmdir /S /Q "' . str_replace('/', '\\', $pluginTarget) . '"');
    } else {
        exec('rm -rf ' . escapeshellarg($pluginTarget));
    }
}
if (!is_dir($pluginTarget) && !is_link($pluginTarget)) {
    ensure_plugin_link($pluginTarget, $pluginSource);
}
echo "Linked lead widget plugin: {$pluginTarget}\n";

require $repoRoot . '/scripts/_wp-bootstrap.php';
require_once ABSPATH . 'wp-admin/includes/plugin.php';

$agentKey = isset($env['KALKTOP_AGENT_KEY']) ? trim($env['KALKTOP_AGENT_KEY']) : '';
if ($agentKey === '' && isset($env['GENERATOR_AGENT_KEY'])) {
    $agentKey = trim($env['GENERATOR_AGENT_KEY']);
}
if ($agentKey === '') {
    $agentKey = (string) get_option('topinstal_calc_agent_api_key', 'calc-agent-key-xyz');
}

$port = getenv('KALK_TOP_RUNTIME_PORT');
$portInt = (is_string($port) && ctype_digit(trim($port))) ? (int) trim($port) : 8091;
$generatorBase = 'http://127.0.0.1:' . $portInt;
$calcRest = $generatorBase . '/wp-json/topinstal/v1/calculate-offer';

update_option('siteurl', $generatorBase);
update_option('home', $generatorBase);
update_option('topinstal_calc_agent_api_key', $agentKey);
update_option('top_instal_agent_api_key', $agentKey);
update_option('topinstal_lead_widget_calc_agent_api_key', $agentKey);
update_option('topinstal_lead_widget_calc_rest_url', $calcRest);
update_option('topinstal_lead_widget_generator_url', $generatorBase);
update_option('topinstal_lead_widget_generator_agent_key', $agentKey);
update_option('topinstal_lead_widget_operator_email', 'konradswierad@gmail.com');
update_option('topinstal_lead_widget_offer_test_mode', '1');
update_option('topinstal_lead_widget_mail_from', isset($env['SMTP_FROM']) ? $env['SMTP_FROM'] : 'biuro.topinstal@gmail.com');

$nodeBBase = isset($env['NODE_B_REGISTRY_BASE_URL']) ? trim($env['NODE_B_REGISTRY_BASE_URL']) : '';
$hostPort = isset($gmailEnv['GMAIL_AGENT_NODEB_PORT']) ? trim($gmailEnv['GMAIL_AGENT_NODEB_PORT']) : '8766';
if ($hostPort === '') {
    $hostPort = '8766';
}
if ($nodeBBase === '' || preg_match('#://127\.0\.0\.1:8765/?$#', $nodeBBase)) {
    $nodeBBase = 'http://127.0.0.1:' . $hostPort;
}
$nodeBToken = '';
foreach (array(
    $repoRoot . '/../gmail-agent/.env.local-vps',
    $repoRoot . '/../gmail-agent/.env.vps',
) as $tokenEnvPath) {
    if (!is_readable($tokenEnvPath)) {
        continue;
    }
    $tokenEnv = parse_dotenv($tokenEnvPath);
    foreach (array('NODE_B_REGISTRY_TOKEN', 'GMAIL_AGENT_INTERNAL_API_TOKEN', 'DASZEK_NODE_B_API_TOKEN') as $token_key) {
        if (isset($tokenEnv[$token_key]) && trim((string) $tokenEnv[$token_key]) !== '') {
            $nodeBToken = trim((string) $tokenEnv[$token_key]);
            break 2;
        }
    }
}
update_option('topinstal_lead_widget_node_b_registry_url', $nodeBBase);
update_option('topinstal_lead_widget_node_b_registry_token', $nodeBToken);
update_option('topinstal_node_b_registry_base_url', $nodeBBase);
update_option('topinstal_node_b_registry_token', $nodeBToken);

if (!is_plugin_active('topinstal-lead-widget/topinstal-lead-widget.php')) {
    activate_plugin('topinstal-lead-widget/topinstal-lead-widget.php');
}

echo "Configured WP options:\n";
echo "  operator_email=konradswierad@gmail.com\n";
echo "  generator_url={$generatorBase}\n";
echo "  calc_rest_url={$calcRest}\n";
echo "  agent_key=" . ($agentKey !== '' ? '[set]' : '[empty]') . "\n";
echo "  offer_test_mode=1\n";
echo "  node_b_registry_url={$nodeBBase}\n";
echo "  node_b_registry_token=" . ($nodeBToken !== '' ? '[set]' : '[empty]') . "\n";
echo '  lead_widget_active=' . (is_plugin_active('topinstal-lead-widget/topinstal-lead-widget.php') ? '1' : '0') . "\n";
echo "CONFIGURE OK\n";
