<?php
/**
 * Configure fast-kalk lead widget + SMTP for local WP runtime (:8090).
 * Run: php scripts/configure-local.php
 */

$repoRoot = dirname(__DIR__);
$wpRoot = $repoRoot . '/../kalk-top/.runtime-wp/wordpress';
$muSource = $repoRoot . '/wp-content/mu-plugins/topinstal-wp-smtp.php';
$muTargetDir = $wpRoot . '/wp-content/mu-plugins';
$muTarget = $muTargetDir . '/topinstal-wp-smtp.php';
$pluginSource = $repoRoot . '/wp-content/plugins/topinstal-lead-widget';
$pluginTarget = $wpRoot . '/wp-content/plugins/topinstal-lead-widget';
$secretsPath = $repoRoot . '/config/local-secrets.env';
$cieploEnv = $repoRoot . '/../cieplo-orchestrator/.env';

/**
 * @param string $path
 * @return array<string,string>
 */
function parse_dotenv($path) {
    $out = array();
    if (!is_readable($path)) {
        return $out;
    }
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') {
            continue;
        }
        $eq = strpos($line, '=');
        if ($eq === false) {
            continue;
        }
        $key = trim(substr($line, 0, $eq));
        $value = trim(substr($line, $eq + 1));
        if ($key !== '') {
            $out[$key] = $value;
        }
    }
    return $out;
}

/**
 * @param string $dir
 * @param string $link
 * @param string $target
 * @return void
 */
/**
 * @param string $link
 * @param string $target
 * @return void
 */
function ensure_plugin_link($link, $target) {
    if (PHP_OS_FAMILY === 'Windows') {
        if (is_dir($link) || is_link($link)) {
            return;
        }
        $parent = dirname($link);
        if (!is_dir($parent)) {
            mkdir($parent, 0755, true);
        }
        $cmd = 'cmd /c mklink /J "' . str_replace('/', '\\', $link) . '" "' . str_replace('/', '\\', $target) . '"';
        exec($cmd, $output, $code);
        if ($code !== 0 && !is_dir($link)) {
            fwrite(STDERR, "Failed to junction plugin: {$link}\n");
            exit(1);
        }
        return;
    }
    symlink($target, $link);
}

function ensure_symlink($dir, $link, $target) {
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    if (is_link($link)) {
        return;
    }
    if (is_file($link)) {
        if (realpath($link) === realpath($target)) {
            return;
        }
        @unlink($link);
    }
    if (PHP_OS_FAMILY === 'Windows') {
        if (!is_file($link)) {
            $cmd = 'cmd /c mklink "' . str_replace('/', '\\', $link) . '" "' . str_replace('/', '\\', $target) . '"';
            exec($cmd, $output, $code);
            if ($code !== 0 && !is_file($link)) {
                copy($target, $link);
            }
        }
        return;
    }
    symlink($target, $link);
}

$env = parse_dotenv($cieploEnv);
$smtpKeys = array('SMTP_HOST', 'SMTP_PORT', 'SMTP_USER', 'SMTP_PASSWORD', 'SMTP_FROM', 'SMTP_USE_SSL', 'SMTP_USE_TLS');
$lines = array('# Generated by configure-local.php — do not commit');
foreach ($smtpKeys as $key) {
    if (isset($env[$key]) && $env[$key] !== '') {
        $lines[] = $key . '=' . $env[$key];
    }
}
if (!is_dir(dirname($secretsPath))) {
    mkdir(dirname($secretsPath), 0755, true);
}
file_put_contents($secretsPath, implode("\n", $lines) . "\n");
echo "Wrote {$secretsPath}\n";

ensure_symlink($muTargetDir, $muTarget, $muSource);
echo "Linked mu-plugin: {$muTarget}\n";

if (is_dir($pluginTarget) && !is_link($pluginTarget) && count(scandir($pluginTarget)) <= 2) {
    rmdir($pluginTarget);
}
if (!is_dir($pluginTarget) && !is_link($pluginTarget)) {
  ensure_plugin_link($pluginTarget, $pluginSource);
}
echo "Linked lead widget plugin: {$pluginTarget}\n";

require $repoRoot . '/scripts/_wp-bootstrap.php';

$agentKey = isset($env['KALKTOP_AGENT_KEY']) ? trim($env['KALKTOP_AGENT_KEY']) : '';
if ($agentKey === '' && isset($env['GENERATOR_AGENT_KEY'])) {
    $agentKey = trim($env['GENERATOR_AGENT_KEY']);
}
if ($agentKey === '') {
    $agentKey = (string) get_option('topinstal_calc_agent_api_key', 'calc-agent-key-xyz');
}

$port = getenv('KALK_TOP_RUNTIME_PORT');
$portInt = (is_string($port) && ctype_digit(trim($port))) ? (int) trim($port) : 8091;
$generatorBase = 'http://127.0.0.1:' . $portInt;
$calcRest = $generatorBase . '/wp-json/topinstal/v1/calculate-offer';

update_option('siteurl', $generatorBase);
update_option('home', $generatorBase);
update_option('topinstal_calc_agent_api_key', $agentKey);
update_option('top_instal_agent_api_key', $agentKey);
update_option('topinstal_lead_widget_calc_agent_api_key', $agentKey);
update_option('topinstal_lead_widget_calc_rest_url', $calcRest);
update_option('topinstal_lead_widget_generator_url', $generatorBase);
update_option('topinstal_lead_widget_generator_agent_key', $agentKey);
update_option('topinstal_lead_widget_operator_email', 'konradswierad@gmail.com');
update_option('topinstal_lead_widget_offer_test_mode', '1');
update_option('topinstal_lead_widget_mail_from', isset($env['SMTP_FROM']) ? $env['SMTP_FROM'] : 'biuro.topinstal@gmail.com');

echo "Configured WP options:\n";
echo "  operator_email=konradswierad@gmail.com\n";
echo "  generator_url={$generatorBase}\n";
echo "  calc_rest_url={$calcRest}\n";
echo "  agent_key=" . ($agentKey !== '' ? '[set]' : '[empty]') . "\n";
echo "  offer_test_mode=1\n";
echo "CONFIGURE OK\n";
